embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/assets/dice/die.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"Material\"\n"
  "  material: \"/light_and_shadows/materials/model/model_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/assets/dice/dice.png\"\n"
  "  }\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 1.0\n"
  "friction: 0.5\n"
  "restitution: 0.5\n"
  "group: \"unit\"\n"
  "mask: \"default\"\n"
  "mask: \"unit\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 1.0\n"
  "  data: 1.0\n"
  "  data: 1.0\n"
  "}\n"
  "linear_damping: 0.8\n"
  "angular_damping: 0.8\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
