embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/examples/tinyworld/models/tree_bill1.gltf\"\n"
  "name: \"unnamed\"\n"
  "materials {\n"
  "  name: \"material_0\"\n"
  "  material: \"/examples/tinyworld/materials/billboard_model_instanced_nearest.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/examples/tinyworld/models/texture.png\"\n"
  "  }\n"
  "}\n"
  "materials {\n"
  "  name: \"material_1\"\n"
  "  material: \"/examples/tinyworld/materials/shadow_mesh/model3.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/examples/tinyworld/models/texture.png\"\n"
  "  }\n"
  "}\n"
  ""
}
