embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"tree3\"\n"
  "material: \"/examples/tinyworld/materials/billboard_light_sprite_nearest.material\"\n"
  "textures {\n"
  "  sampler: \"tex0\"\n"
  "  texture: \"/examples/tinyworld/tiles.atlas\"\n"
  "}\n"
  "textures {\n"
  "  sampler: \"tex1\"\n"
  "  texture: \"/examples/tinyworld/tiles.atlas\"\n"
  "}\n"
  "textures {\n"
  "  sampler: \"fow\"\n"
  "  texture: \"/examples/tinyworld/tiles.atlas\"\n"
  "}\n"
  ""
}
