embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/examples/fow/models/block.gltf\"\n"
  "name: \"unnamed\"\n"
  "materials {\n"
  "  name: \"material_0\"\n"
  "  material: \"/examples/fow/materials/fog _of_ war/model_fow.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/examples/fow/models/texture.png\"\n"
  "  }\n"
  "}\n"
  ""
}
